---
- hosts: all
  become: yes
  tasks:
    # Installation
    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install dependences
      apt:
        pkg:
          # required to install pyenv
          - git
          # required by pyenv install x
          - build-essential
          - zlib1g-dev
          - libssl-dev
          # required to enable python extensions
          - libreadline-dev
          - libsqlite3-dev
          - libbz2-dev

    - name: Get source for pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv
        clone: yes
        update: yes
    - name: Build pyenv
      command: src/configure && make -C src
      args:
        chdir: ~/.pyenv
    - name: Make pyenv binary accessible without shell magic
      file:
        src: ~/.pyenv/bin/pyenv
        path: /usr/local/bin/pyenv
        state: link
    - name: Make pyenv's shims accessible
      copy:
        dest: /etc/profile.d/custom-path.sh
        content: 'PATH=/root/.pyenv/shims:$PATH'
    - name: Install the required python version under pyenv
      # TODO read out from .python-version
      ansible.builtin.command:
        cmd: pyenv install 3.9.9
        creates: /root/.pyenv/versions/3.9.9

    # Application environment configuration
    - name: Create working folder for application
      file:
        path: /server
        state: directory
    - name: Prepare python environment
      shell: |
        echo "3.9.9" > .python-version
        export PATH=/root/.pyenv/shims:$PATH
        echo $PATH > the_path_at_exec
        python -m venv venv
      args:
        chdir:
          /server
        creates:
          /server/venv
    - name: Add requiremets.txt
      copy:
        dest: /server
        src: ../requirements.txt
    - name: Install python modules
      pip:
        requirements: /server/requirements.txt
        virtualenv: /server/venv

    # - name: Install python
    #   apt:
    #     pkg:
    #       - python3
    #       - python3-pip
    #       - virtualenv
    #       - python3-setuptools
    #
    # - name: Add application code
    #   copy:
    #     src: ../oracle
    #     dest: /server/
    #
    #

    # Nginx
    - name: Install nginx
      apt:
        name: nginx
    - name: Add page to serve
      copy:
        dest: /var/www/html/index.nginx-debian.html
        src: ./test.html
